# ---- Site ----
repository: sproogen/resume-theme
favicon: images/favicon.ico

# ---- Content configuration version ----
version: 2

# ---- Personal info ----
name: Emma DeJong
title: Software Engineer
email: dejong.l.emma@gmail.com
website: emmaldejong.github.io

# ---- Dark Mode (true/false/never) ----
darkmode: true

# ---- Social links ----
github_username:  emmaldejong
linkedin_username: emmaldejong
# twitter_username: --
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: emmaldejong
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# ---- Additional icon links ----
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# ---- Google Analytics and Tag Manager ----
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# ---- About Section ----
# about_title: About Me
about_profile_image: images/EMMA.png
about_content: | 
  Hi, my name's Emma and I'm a software engineer. I've been working as a professional programmer for 3 years and it has been a really exciting journey. When I was working as a Salesforce Administrator at the San Antonio Humane Society, I had some exposure to what programming as a career could look like. While that role did not require any programming, I was always curious about how Salesforce as an applicaiton worked behind the scenes to provide me the views and functionality I used everday.

  Around 2018, I started to notice billboards on my drive to work for a coding bootcamp and decided it was worth a look. Shortly after, I attended and completed Codeup's web development bootcamp in San Antonio and while that was one of the harder things I've accomplished, it was one of the most fun times I've had.

  I was hired at Brokerage Engine about 2 weeks before my actual graduation in Codeup. BrokerageEngine was a very small start up in San Antonio at that time and it was the best first programming job I could have asked for. Because of how small the development team was (*4 people, including myself and one of my classmates from Codeup*), I had the opportunity to touch every part of our codebase, learn completely new languages than what I had learned in my bootcamp, and I was lucky enough to have managers that invested in my career and enjoyed helping me grow and learn during that time. This job solidified my love for the career I had chosen.

  In 2019, I started my next job at CaptureRx in San Antonio as well. This job gives me the opportunity to work with a different style of system architecture and have the experience of working and coordinating with a larger development team. I've had the opportunity to assist in preparing for an eventual move to Docker/Kubernetes and some exposure to AWS in addition to my day to day programmer responsibilities. 

content:
  - title: Programming Skills
    layout: list
    content:
      - layout: top-middle
        description: |
         - TESTING PUSHES Server Side Technologies [ *Ruby on Rails, Java* ]
         - Client Side Technologies [ *React* ]
         - API Development [ *GraphQL, Rest* ]
         - RDBMs [ *PostgresQL* ]
         - Testing [ *RSpec, JUnit* ]
      
  - title: Experience # ---- Title for the section ----
    layout: list # ---- Type of content section (list/text) ----
    content:
    - layout: left
        title: PayNearMe
        link: https://home.paynearme.com/
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: July 2021 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | 
          - Wrote production Rails scripts to make updates to data or processes for customer requests 
          - Researched feature requests to help provide technical requirements for stories
          - Rolled out fixes for system bugs after identifying the issue and communicating a proposed solution to necessary team members
          - Created and implemented technical architecture for third party API integration for a newly launching enterprise customer

      - layout: left
        title: CaptureRx
        link: capturerx.com
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: August 2019 - June 2021
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | 
          - Designed and implemented features for the new system based on business requirements using predominantly Java and Angular 
          - Performed timely analysis of production bugs and worked to execute immediate solutions
          - Researched and provided discovery to the team for system analysis, architectural design and potential use of new technology
          - Kept up to date technical documentation on any new code pushed into beta or production environments

      - layout: left
        title: Brokerage Engine
        link: brokerageengine.com
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: June 2018 - July 2019
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Provided architecture design and maintained quality code for a real estate transaction calculation system primarily using Ruby on Rails, Graphql and React
          - Orchestrated and executed timelines and feature roll outs for larger, extensive projects 
          - Worked with other developers and client-facing team members to quickly and effectively identify system bugs and implement solutions
          - Maintained quality code through the use of test driven development and refactoring procedures

      - layout: left
        title: San Antonio Humane Society
        link: sahumane.org
        # link_text: boringcompany.com
        sub_title: Salesforce Administrator
        caption: May 2014 - January 2018
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Implemented and managed the migration of Salesforce to replace the previous legacy donor database system
          - Ensured data quality through rigorous data management to produce efficient reporting for users
          - Prepared data and reconciled accounts for monthly financial reporting

  - title: Projects # ---- Title for the section ----
    layout: list # ---- Type of content section (list/text) ----
    content:
      - layout: left
        title: Pawtify / Geekdom Incubator Program
        link: https://www.youtube.com/watch?v=3p79oTpAkfY&ab_channel=Geekdom
        link_text: Geekdom Incubator 2020 Demo Video
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fa fa-paw
            # url: pawtifysa.com
        description: | 
          Pawtify originally was my final capstone project for Codeup. It started as a notifcation system for potential adopters to more easily match with shelter pets that met their pre-selected criteria. Through the Geekdom Incubator system, it transformed into present day Pawtify, a shelter adopiton management app and the beginings of a full scale shelter management system. The project is just finished being taken through a Civic Tech focused incubator with GeekdomSA and the City of San Antonio and is being developed in NodeJs, React and GraphQL.	
            
  - title: Education # ---- Title for the section ----
    layout: list # ---- Type of content section (list/text) ----
    content:
      - layout: left
        title: Codeup
        caption: January 2018 - May 2018
        sub_title: Web Development Completion Certificate
        # quote: >
        description: | 
          Codeup is a fully-immersive, project-based 18 week full stack Java career accelerator that provides students with 603+ hours of expert instruction in software development.
          There I learned programming fundamentals in HTML, CSS, Javascript and moved on to learn MySQL, Java and the springboot framework to compile our final capstone project for the course.

      - layout: left
        title: DePaul university
        caption: August 2012 - May 2014
        sub_title: Concentration in Accounting & Finanace
        # quote: >
        #   blurb
        description: | 
          At DePaul, my studies were focused in accounting and finance as well as my general studies courses during my time that I was there. I also was a member for Alpha Omnicron Pi Fraternity while I was there and served as there Assistant Treasurer and Treasurer while I was an active member.  

  - title: A Little More About Me
    layout: text
    content: | 
      Alongside my interests and professional career in software engineering, some of my other hobbies are:
      - Tarnatula Husbandry/Keeping
      - Getting My Private Pilots License
      - Hanging Out with My Cats
      - Hiking or Swimming
  
      ![Grid](/images/grid.jpeg "Grid")

# ---- Footer ----
footer_show_references: true
# references_title: References on request (Override references text)

# ---- Build settings ----
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
